const languages = [
  "HTML",
  "CSS",
  "VANILLA JAVASCRIPT",
  "SASS/SCSS",
  "TYPESCRIPT",
];

const frameworks = [
  "React.js",
  "Next.js",
  "Redux Toolkit",
  "Node.js",
  "Express.js",
  "PostgreSQL",
  "Prisma",
  "MongoDB",
  "Nest.js",
  "Bootstrap",
  "Tailwind CSS",
  "Material UI",
  "Ant Design",
  "Git",
  "Postman",
];

const projects = [
  {
    title: "Portfolio V2",
    development: ["Frontend"],
    github: "https://github.com/sawnaytharpoe02/PortofolioV2",
    stacks: ["React", "Tailwindcss", "Vite", "Framer-motion", "Gsap"],
    year: "2024",
  },
  {
    title: "Blog",
    development: ["Fullstack"],
    github: "https://github.com/sawnaytharpoe02/laravel-duraBlog",
    stacks: ["Laravel", "Tailwindcss", "AOS", "Digital Ocean"],
    year: "2023",
  },
  {
    title: "Duralumin Blog",
    development: ["Frontend"],
    href: "https://duralumin-blog.vercel.app",
    stacks: ["Html", "Css", "Vite"],
    year: "2023",
  },
  {
    title: "Task Management System",
    development: ["Fullstack", "Collaborative Task"],
    github: "https://github.com/sawnaytharpoe02/TaskMng_NextNest",
    stacks: ["NestJS", "React", "MongoDB", "Material UI"],
    year: "2023",
  },
  {
    title: "Social Media App",
    development: ["Fullstack", "Collaborative Task"],
    github: "https://github.com/sawnaytharpoe02/gp-socialmedia-app",
    stacks: ["React", "Css", "Nodejs", "MongoDB"],
    year: "2023",
  },
  {
    title: "Todo List",
    development: ["Frontend"],
    href: "https://to-todo.vercel.app",
    stacks: ["React", "Css"],
    year: "2023",
  },
  {
    title: "Media API",
    development: ["Backend"],
    github: "https://github.com/sawnaytharpoe02/media-api",
    stacks: ["ExpressJs", "MongoDB"],
    year: "2023",
  },
  {
    title: "Meme Generator",
    development: ["Frontend"],
    href: "https://create-meme.vercel.app",
    stacks: ["React", "Css", "Vite"],
    year: "2023",
  },
  {
    title: "Foodie Mody",
    development: ["Frontend"],
    href: "https://foodie-mody.netlify.app",
    stacks: ["Html", "Bootstrap", "Javascript", "Vite"],
    year: "2022",
  },
  {
    title: "Booky Landy",
    development: ["Frontend"],
    href: "https://bookylandy.netlify.app",
    stacks: ["Html", "Scss", "Boostrap"],
    year: "2022",
  },
  {
    title: "Cycle Studio",
    development: ["Frontend"],
    href: "https://cyclestudio.netlify.app",
    stacks: ["Html", "Scss", "Gsap"],
    year: "2022",
  },
  {
    title: "SnapLand",
    development: ["Frontend"],
    href: "https://snapland.netlify.app",
    stacks: ["Html", "Boostrap"],
    year: "2022",
  },

  {
    title: "BeeGarden",
    development: ["Frontend"],
    href: "https://beegarden.netlify.app",
    stacks: ["html", "Scss", "Javascript", "Gsap", "Vite"],
    year: "2022",
  },
  {
    title: "Fortress Clash",
    development: ["Design"],
    href: "https://fortress-clash.netlify.app",
    stacks: ["Html", "Css", "Swiper"],
    year: "2022",
  },
  {
    title: "Premium Dashboard",
    development: ["Frontend"],
    href: "https://bootboard.vercel.app",
    stacks: ["Vite", "Bootstrap", "Javascript", "Apexchart", "JsVectorMap"],
    year: "2022",
  },
  {
    title: "Music Tracker",
    development: ["Design"],
    href: "https://music-track.netlify.app",
    stacks: ["Html", "Css", "Javascript"],
    year: "2022",
  },
];

const featuredProjects = [
  {
    title: "Taskito",
    href: "https://taskito.vercel.app/login",
    repo: "https://github.com/sawnaytharpoe02/TaskMng_ReactNode",
    description:
      "Taskito is a fullstack app that streamlines project and task management for teams. Admins create users, who can manage projects, assign tasks with real-time alerts, and use search, filtering, and export features for tasks and reports.",
    tech: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Ant Design",
      "Cloudinary",
      "Socket.io",
    ],
    demoCredentials: {
      email: "sawnaytharpoe14@gmail.com",
      password: "admin123",
    },
    bgColor: "#274546",
    titleColor: "#efeee5",
  },
  {
    title: "Forklore",
    href: "https://food-ordering-sym.vercel.app",
    repo: "https://github.com/sawnaytharpoe02/rest-pos",
    description:
      "Forklore is a food ordering app for restaurants. Customers scan a QR code for user-friendly menus, and admins manage menus, categories, addons, and more. Delicious efficiency!",
    tech: [
      "Next.js",
      "Typescript",
      "Redux Toolkit",
      "Material UI",
      "Prisma",
      "PostgreSQL",
      "S3 Storage",
    ],
    bgColor: "#efeee5",
    titleColor: "#274546",
  },
  {
    title: "MyBento MyFolio",
    href: "https://my-bento-my-folio.vercel.app/",
    repo: "https://github.com/sawnaytharpoe02/myBentomyFolio",
    description:
      "Mybento myFolio is a vibrant showcase of my passion for trendy bento designs. It's not just a portfolio; it's a dynamic gallery capturing my current creative journey, celebrating the art of bento with a fresh, modern twist.",
    tech: [
      "Next.js",
      "Typescript",
      "Framer Motion",
      "Tailwindcss",
      "Next Themes",
    ],
    bgColor: "#232323",
    titleColor: "#fbf8f3",
  },
  {
    title: "BankInc",
    href: "https://bank-inc.vercel.app/",
    repo: "https://github.com/sawnaytharpoe02/banking-mng-sym",
    description:
      "This project is a mini banking management system built to practice and apply the foundational and latest features of Next.js. It efficiently handles customer accounts, transactions, and basic banking activities.",
    tech: ["NextJS", "Typescript", "Postgresql", "ChadcnUI"],
    bgColor: "#fbf8f3",
    titleColor: "#232323",
  },
];

const loaderData = [
  "Backend",
  "Debug",
  "Deploy",
  "Framework",
  "Design",
  "Code",
  "Frontend",
  "Repository",
  "Syntax",
  "Versioning",
  "Refactor",

  "Backend",
  "Debug",
  "Deploy",
  "Framework",
  "Design",
  "Code",
  "Frontend",
  "Repository",
  "Syntax",
  "Versioning",
  "Refactor",

  "Backend",
  "Debug",
  "Deploy",
  "Framework",
  "Design",
  "Code",
  "Frontend",
  "Repository",
  "Syntax",
  "Versioning",
  "Refactor",

  "Backend",
  "Debug",
  "Deploy",
  "Framework",
  "Design",
  "Code",
  "Frontend",
  "Repository",
  "Syntax",
  "Versioning",
  "Refactor",

  "Backend",
  "Debug",
  "Deploy",
  "Framework",
  "Design",
  "Code",
  "Frontend",
  "Repository",
  "Syntax",
  "Versioning",
  "Refactor",
];

export { languages, frameworks, projects, featuredProjects, loaderData };
